name: gpfwa
services:

  pg-data:
    image: busybox:latest
    command: echo "PostgreSQL data only container"
    volumes:
      - ./gpfwa-pg-data:/var/lib/postgresql

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    volumes_from:
      - pg-data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gpfwa
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mail:
    image: mailhog/mailhog
    hostname: mail
    ports:
      - "8025:8025"

  backend-migrate:
    image: ${BACKEND_IMAGE:-gain-web-api-prod:latest}
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: web_annotation.settings_gunicorn
      GPFWA_DB_NAME: gpfwa
      GPFWA_DB_USER: postgres
      GPFWA_DB_PASSWORD: secret
      GPFWA_DB_HOST: db
      GPFWA_DB_PORT: 5432
      GPFWA_SECRET_KEY: "django-insecure-3rz4n(_u+x8r+n%&xr-(vg83v8&llq7pin*x%@%y@d8af%iphk"
    entrypoint: ["python", "-m", "django", "migrate", "--noinput"]
    restart: "no"

  backend:
    image: ${BACKEND_IMAGE:-gain-web-api-prod:latest}
    depends_on:
      backend-migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      mail:
        condition: service_started
    volumes:
      - ./gpfwa-data:/data
      - ./gpfwa-logs:/logs
      - /mnt/wigclust3/data/unsafe/chorbadj/grr.sync:/grr
    environment:
      DJANGO_SETTINGS_MODULE: web_annotation.settings_gunicorn
      GPFWA_EMAIL_HOST: mail
      GRR_DEFINITION_FILE: /grr-definition-dir.yaml
      GPFWA_DB_NAME: gpfwa
      GPFWA_DB_USER: postgres
      GPFWA_DB_PASSWORD: secret
      GPFWA_DB_HOST: db
      GPFWA_DB_PORT: 5432
      GPFWA_DATA_STORAGE: /data
      GPFWA_LOG_DIR: /logs
      GPFWA_SECRET_KEY: "django-insecure-3rz4n(_u+x8r+n%&xr-(vg83v8&llq7pin*x%@%y@d8af%iphk"
      GPFWA_EMAIL_VERIFICATION_ENDPOINT: "http://wigclust3.cshl.edu:8000"
      GPFWA_EMAIL_REDIRECT_ENDPOINT: "http://wigclust3.cshl.edu:8000"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9001/api/user_info"]
      interval: 10s
      timeout: 5s
      retries: 5


  frontend:
    image: ${FRONTEND_IMAGE:-gain-web-ui-prod:latest}
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
    - "8000:80"
