pipeline {
    agent { label 'eyoree' }
    options {
        quietPeriod(0);
        copyArtifactPermission('/iossifovlab/*,/seqpipe/*');
        disableConcurrentBuilds()
    }
    environment {
        COMPOSE_PROJECT_NAME = "gpfwa-${env.BRANCH_NAME}-${env.BUILD_NUMBER}"
    }

    triggers {
        upstream(upstreamProjects: 'iossifovlab/gpf-conda-packaging/master', threshold: hudson.model.Result.SUCCESS)
    }

    stages {
        stage('Start') {
            steps {
                dir('web_infra') {
                    sh "echo 'Starting build ${COMPOSE_PROJECT_NAME}'"
                    sh "docker run --rm -v ..:/wd --entrypoint '/usr/bin/bash' ubuntu:24.04 -c 'rm -rf /wd/web_infra/results /wd/web_infra/reports /wd/web_api/reports /wd/web_ui/reports /wd/web_e2e/reports /wd/web_infra/gpfwa-logs /wd/web_infra/gpfwa-data'"
                    sh "rm -rf conda-channel"
                }
                zulipSend(
                    message: "Started build #${env.BUILD_NUMBER} of project ${env.JOB_NAME} (${env.BUILD_URL})",
                topic: "${env.JOB_NAME}")
            }
        }

        stage('Copy artifacts') {
            steps {
                dir('web_infra') {
                    copyArtifacts(
                        filter: "results/conda-channel.tar.gz",
                        fingerprintArtifacts: true,
                        projectName: "iossifovlab/gpf-conda-packaging/master",
                        selector: lastSuccessful()
                    )
                    sh "tar -xzf results/conda-channel.tar.gz"
                }
            }
        }

        stage('Build') {
            steps {
                dir('web_infra') {
                    sh "docker compose -f compose-jenkins.yaml build ubuntu-image"
                    sh "docker compose -f compose-jenkins.yaml build gpf-image"
                    sh "docker compose -f compose-jenkins.yaml down --remove-orphans"
                }
            }
        }

        stage('Build Backend image') {
            steps {
                dir('web_infra') {
                    sh "docker compose -f compose-jenkins.yaml build backend-e2e"
                }
            }
        }

        stage('Build Frontend image') {
            steps {
                dir('web_infra') {
                    sh "docker compose -f compose-jenkins.yaml build frontend-e2e"
                }
            }
        }

        stage('Run E2E Tests') {
            steps {
                dir('web_infra') {
                    sh "docker compose -f compose-jenkins.yaml build backend-e2e"
                    sh "docker compose -f compose-jenkins.yaml build frontend-e2e"
                    sh "docker compose -f compose-jenkins.yaml build e2e-tests"
                    sh "mkdir -p ../web_e2e/reports"
                    sh "docker compose -f compose-jenkins.yaml down --remove-orphans"
                    sh "docker compose -f compose-jenkins.yaml run --rm --remove-orphans e2e-tests || true"
                    sh "mkdir -p reports"
                    sh "cp ../web_e2e/reports/junit-report.xml reports/e2e-junit-report.xml"
                }
            }
        }


    }

  post {
    always {
      script {
        dir('web_infra') {
            sh "docker compose -f compose-jenkins.yaml down --remove-orphans"
            sh "mkdir -p logs; gzip -c gpfwa-logs/gpfwa-debug.log > logs/gpfwa-debug.log.gz || true"
        }


        try {

            archiveArtifacts artifacts: 'web_e2e/reports/**', fingerprint: false, allowEmptyArchive: true
            archiveArtifacts artifacts: 'web_infra/logs/gpfwa-debug.log.gz', fingerprint: true, allowEmptyArchive: true

            discoverGitReferenceBuild(latestBuildIfNotFound: true, maxCommits: 400, skipUnknownCommits: true)

            def resultBeforeTests = currentBuild.currentResult
            currentBuild.result = 'SUCCESS'
            junit 'web_infra/reports/*-junit-report.xml'

            sh "test ${resultBeforeTests} == ${currentBuild.currentResult}"
            currentBuild.result = resultBeforeTests

        } finally {
          zulipNotification(
            topic: "${env.JOB_NAME}"
          )
        }
      }
    }
  }
}
