"""The resource types the fixture GRR has to supply itself.

``mini-GRR`` is the repository GAIn's own onboarding documentation hands to
new users (``docs/source/gain_getting_started_grr.rst``), and it covers the
eight resource types that documentation is about.  Four registered
implementations are outside that scope -- ``liftover_chain``, ``basic``,
``data_frame`` and ``ann_data`` -- and they are built here instead of being
pushed upstream: mini-GRR teaches, and a resource added only to satisfy
GAIn's CI would make it a worse teaching example (gain#991).

Every resource here is realized from the builders in
:mod:`gain.genomic_resources.testing`, so the shapes stay honest as those
builders move.  Nothing in this module may import ``scanpy``: the ``core``
CI image installs only ``--group dev``, and scanpy arrives solely with the
integration image's ``--group scanpy-drift`` (ADR 0014).  The local
development venv does have it, so a green local run does not prove this --
the import fence in ``test_info_pages`` does.
"""
from __future__ import annotations

import pathlib
import textwrap

from gain.genomic_resources.testing import (
    convert_to_tab_separated,
    setup_directories,
    setup_gzip,
)
from gain.genomic_resources.testing.ann_data_builder import an_ann_data
from gain.genomic_resources.testing.data_frame_builder import a_data_frame

#: Resource ids for the in-repo supplements, keyed by the resource ``type:``
#: they exist to cover.  The suite reads this to report which fixture stands
#: behind which implementation, so it is the mapping and not a bare list.
SUPPLEMENT_RESOURCE_IDS = {
    "liftover_chain": "supplement_liftover_chain",
    "basic": "supplement_basic",
    "data_frame": "supplement_data_frame",
    "ann_data": "supplement_ann_data",
}

# Three chains over three contigs, lifted from the shape the liftover
# annotator tests already use (``tests/small/conftest.py``).  Small enough to
# read, wide enough that the page renders a real chain table rather than an
# empty one.
_LIFTOVER_CHAIN_DATA = """
chain 4900 foo 104 + 4 104 chrFoo 100 + 0 96 1
48 4 0
48 0 0
0

chain 4800 bar 112 + 4 108 chrBar 100 + 0 96 2
48 8 0
48 0 0
0

chain 4700 baz 108 + 4 104 chrBaz 100 - 4 100 3
48 4 0
48 0 0
0
"""


def add_supplement_resources(repo_dir: pathlib.Path) -> None:
    """Realize the four in-repo supplement resources into ``repo_dir``.

    Called on the copy of mini-GRR, before ``repo-stats``, so the supplements
    are indexed, get statistics computed and get pages generated by exactly
    the same run that covers mini-GRR's own resources.
    """
    _add_basic(repo_dir / SUPPLEMENT_RESOURCE_IDS["basic"])
    _add_liftover_chain(repo_dir / SUPPLEMENT_RESOURCE_IDS["liftover_chain"])
    a_data_frame().realize_into(
        repo_dir / SUPPLEMENT_RESOURCE_IDS["data_frame"])
    an_ann_data().realize_into(
        repo_dir / SUPPLEMENT_RESOURCE_IDS["ann_data"])


def _add_basic(resource_dir: pathlib.Path) -> None:
    """A ``basic`` resource: a config, a ``meta`` block and one data file.

    ``BasicResourceImplementation`` exposes every manifest entry as a file, so
    the data file is what makes its Files section non-trivial.
    """
    setup_directories(resource_dir, {
        "genomic_resource.yaml": textwrap.dedent("""
            type: basic
            meta:
                summary: |
                    A catch-all resource, carried so the `basic`
                    implementation has a page in the fixture repository.
        """),
        "notes.txt": "a data file, so the Files section has something in it\n",
    })


def _add_liftover_chain(resource_dir: pathlib.Path) -> None:
    """A ``liftover_chain`` resource: a config plus the gzipped chain file."""
    setup_directories(resource_dir, {
        "genomic_resource.yaml": textwrap.dedent("""
            type: liftover_chain
            filename: liftover.chain.gz
        """),
    })
    setup_gzip(
        resource_dir / "liftover.chain.gz",
        convert_to_tab_separated(_LIFTOVER_CHAIN_DATA),
    )
