"""Build the #321 real-coordinate *extra* corpus manifest.

The de-rebased #320 corpus (``test_spliceai_integration``) already exercises the
real GRR comprehensively on chr21, but it is bounded by the committed fixture:
it only touches SON/DONSON/COL6A2, and its two synthetic-gene rejection variants
have no real analog.  This builder adds breadth the fixture cannot hold --
variants at *real* GENCODE splice sites on other chromosomes (both strands) plus
a real near-chromosome-end refusal -- as ``real``-coordinate variants annotated
directly through the node-local GRR.

Deterministic (no RNG): coordinates are computed from the real gene models, so
re-running rewrites ``extra_manifest.json`` byte-identically unless the real
resources move.  The committed ``baseline_extra.json.gz`` (regenerated by
``regenerate_baseline_extra.py`` through TensorFlow) value-pins all 16
attributes at these loci, so drift in the real hg38/GENCODE surfaces as a
red test.

Requires the real GRR (``GRR_ROOT`` env var, default
``/data/cephfs/seqpipe/grr``).  Does NOT run TensorFlow.

Run:  ``python -m tests.corpus.build_extra_corpus``  (from spliceai_annotator).
"""
from __future__ import annotations

import json
import os
import pathlib
from dataclasses import asdict, dataclass
from typing import Any

from gain.genomic_resources.gene_models.gene_models import GeneModels
from gain.genomic_resources.reference_genome import (
    build_reference_genome_from_resource_id,
)
from gain.genomic_resources.repository_factory import (
    build_genomic_resource_repository,
)

GRR_ROOT = os.environ.get("GRR_ROOT", "/data/cephfs/seqpipe/grr")
GENE_MODELS_ID = "hg38/gene_models/GENCODE/49/comprehensive/CHR"
GENOME_ID = "hg38/genomes/GRCh38.p14"

HERE = pathlib.Path(__file__).parent
EXTRA_MANIFEST_PATH = HERE / "extra_manifest.json"

# Breadth genes: one + strand (chr13) and one - strand (chr17), both far from
# the fixture's chr21 loci, so this tier reads real GENCODE on other
# chromosomes and both strands.  The transcript is picked deterministically
# (lowest tr_id among those with >= 4 exons) so the coordinates are stable.
BREADTH_GENES = ("BRCA2", "BRCA1")
# Distances chosen to exercise both tiering regimes: 50 (positions gated tight)
# and 500 (wider window).
BREADTH_DISTANCES = (50, 500)

# A fixed ref->alt map so every variant is a real single-base change (no RNG).
_ALT = {"A": "C", "C": "G", "G": "C", "T": "A"}

# Near-chromosome-end refusal on real resources: chrM is tiny (16569 bp) and
# fully gene-covered, so a variant inside MT-TP near the terminus has a real
# transcript AND a read window that runs off the end -> the annotator's
# "near chromosome end" refusal (spliceai_annotator.py).  This is the only real
# refusal axis re-coverable here; the mixed-strand refusal is a *within-gene*
# check that real GENCODE never triggers, so it stays in the #320 fixture tier.
MT_NEAR_END_CHROM = "chrM"
MT_NEAR_END_POS = 16000
MT_NEAR_END_DISTANCE = 50


@dataclass
class ExtraVariant:
    """One real-coordinate variant in the extra corpus."""

    id: str
    contig: str
    pos: int
    ref: str
    alt: str
    distance: int
    category: str
    expect: str
    reason: str


def _pick_transcript(gene_models: GeneModels, gene: str) -> Any:
    """Lowest-tr_id transcript of ``gene`` with >= 4 exons (deterministic)."""
    candidates = [
        t for t in gene_models.transcript_models.values()
        if t.gene == gene and len(t.exons) >= 4
    ]
    if not candidates:
        raise RuntimeError(
            f"no >=4-exon transcript for {gene} in {GENE_MODELS_ID}")
    return sorted(candidates, key=lambda t: t.tr_id)[0]


def build_variants(grr: Any) -> list[ExtraVariant]:
    """Compute the extra-corpus variants from the real GRR (deterministic)."""
    genome = build_reference_genome_from_resource_id(GENOME_ID, grr)
    genome.open()
    gene_models = GeneModels(grr.get_resource(GENE_MODELS_ID))
    gene_models.load()

    variants: list[ExtraVariant] = []
    for gene in BREADTH_GENES:
        transcript = _pick_transcript(gene_models, gene)
        # An internal donor (end of exon 2) and acceptor (start of exon 3):
        # variants at a real splice dinucleotide give a strong real splice
        # signal to pin.
        sites = {
            "donor": transcript.exons[1].stop,
            "acceptor": transcript.exons[2].start,
        }
        for site_name, pos in sites.items():
            ref = genome.get_sequence(transcript.chrom, pos, pos)
            variants.extend(
                ExtraVariant(
                    id=f"{gene.lower()}_{site_name}_d{distance}",
                    contig=transcript.chrom,
                    pos=pos,
                    ref=ref,
                    alt=_ALT[ref],
                    distance=distance,
                    category="real_splice_site",
                    expect="annotated",
                    reason="",
                )
                for distance in BREADTH_DISTANCES
            )

    ref = genome.get_sequence(
        MT_NEAR_END_CHROM, MT_NEAR_END_POS, MT_NEAR_END_POS)
    variants.append(ExtraVariant(
        id="mt_reject_near_end",
        contig=MT_NEAR_END_CHROM,
        pos=MT_NEAR_END_POS,
        ref=ref,
        alt=_ALT[ref],
        distance=MT_NEAR_END_DISTANCE,
        category="reject",
        expect="rejected",
        reason="near_chromosome_end",
    ))
    return variants


def main() -> None:
    """Build and write the extra-corpus manifest."""
    grr = build_genomic_resource_repository(
        {"id": "real", "type": "directory", "directory": GRR_ROOT})
    variants = build_variants(grr)
    manifest = {
        "genome_resource": GENOME_ID,
        "gene_models_resource": GENE_MODELS_ID,
        "variants": [asdict(v) for v in variants],
    }
    EXTRA_MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"extra manifest: {len(variants)} variants -> {EXTRA_MANIFEST_PATH}")


if __name__ == "__main__":
    main()
