# pylint: disable=W0621,C0114,C0116,W0212,W0613
"""Differential test harness for the SpliceAI annotator (issue #320).

Pins all 16 attributes of today's TensorFlow output on a frozen hg38/GENCODE
fixture corpus, so the upcoming ONNX migration (#297/#299) has real ground
truth to check against.  Two independent checks per variant:

* live annotation vs the committed TensorFlow ``baseline.json.gz`` -- tiered by
  measured stability and by each field's own resolution: the raw ``DS_*`` at
  1e-5, the 4dp probability vectors at 2e-4 (their 4dp grid is not portable any
  tighter), and ``DP_*`` / ``delta_score`` only when ``DS_MAX`` clears the
  argmax noise floor;
* ``batch_annotate`` == ``annotate`` across the whole corpus -- with the same
  tiering (labels exact, probabilities at 2e-4, ``DS_*`` at 1e-5, positions
  gated on ``DS_MAX``).

The tiered assertions live in ``tests/corpus/assertions.py`` (shared with the
#321 node-local-real-GRR tier, which reuses this same baseline and tiering).
The corpus + baseline are regenerated by ``tests/corpus/build_corpus.py`` and
``tests/corpus/regenerate_baseline.py``.
"""
import gzip
import json
import pathlib
from collections import defaultdict
from collections.abc import Iterator
from typing import Any

import pytest
from gain.annotation.annotation_factory import load_pipeline_from_yaml
from gain.annotation.annotation_pipeline import AnnotationPipeline
from gain.genomic_resources.repository import GenomicResourceRepo

from tests.corpus.assertions import (
    allele,
    assert_batch_equals_sequential,
    assert_matches_baseline,
)
from tests.corpus.pipeline_config import make_pipeline_yaml

# Slow: ~9-10 min under TensorFlow. Runs in the gain-spliceai-integration job,
# not the fast per-PR spliceai_annotator step (see spliceai_annotator/pytest.ini
# and the "Trigger spliceai integration" stage in the root Jenkinsfile).
pytestmark = pytest.mark.integration

CORPUS_DIR = pathlib.Path(__file__).parent / "corpus"
MANIFEST = json.loads((CORPUS_DIR / "corpus_manifest.json").read_text())
with gzip.open(CORPUS_DIR / "baseline.json.gz", "rb") as _bf:
    BASELINE: dict[str, dict[str, Any]] = json.loads(_bf.read())

VARIANTS = MANIFEST["variants"]
DISTANCES = sorted({v["distance"] for v in VARIANTS})
_BY_DISTANCE: dict[int, list[dict[str, Any]]] = defaultdict(list)
for _v in VARIANTS:
    _BY_DISTANCE[_v["distance"]].append(_v)


@pytest.fixture(scope="session")
def differential_pipelines(
    spliceai_grr: GenomicResourceRepo,
) -> Iterator[dict[int, AnnotationPipeline]]:
    """One opened all-16-attribute pipeline per corpus distance."""
    pipelines = {}
    for distance in DISTANCES:
        pipeline = load_pipeline_from_yaml(
            make_pipeline_yaml(distance), spliceai_grr)
        pipelines[distance] = pipeline.open()
    yield pipelines
    for pipeline in pipelines.values():
        pipeline.close()


@pytest.mark.parametrize(
    "variant", VARIANTS, ids=[v["id"] for v in VARIANTS])
def test_matches_tensorflow_baseline(
    variant: dict[str, Any],
    differential_pipelines: dict[int, AnnotationPipeline],
) -> None:
    pipeline = differential_pipelines[variant["distance"]]
    result = pipeline.annotate(allele(variant))
    assert_matches_baseline(variant, result, BASELINE)


@pytest.mark.parametrize("distance", DISTANCES)
def test_batch_equals_sequential(
    distance: int,
    differential_pipelines: dict[int, AnnotationPipeline],
) -> None:
    pipeline = differential_pipelines[distance]
    variants = _BY_DISTANCE[distance]
    alleles = [allele(v) for v in variants]

    seq_results = [pipeline.annotate(a) for a in alleles]
    batch_results = pipeline.batch_annotate(alleles)
    assert len(batch_results) == len(variants)

    for variant, seq_result, batch_result in zip(
            variants, seq_results, batch_results, strict=True):
        assert_batch_equals_sequential(variant, seq_result, batch_result)
