# pylint: disable=W0621,C0114,C0116,W0212,W0613
"""Differential test harness for the SpliceAI annotator (issue #320).

Pins all 16 attributes of today's TensorFlow output on a frozen hg38/GENCODE
fixture corpus, so the upcoming ONNX migration (#297/#299) has real ground
truth to check against.  Two independent checks per variant:

* live annotation vs the committed TensorFlow ``baseline.json.gz`` -- tiered by
  measured stability and by each field's own resolution: the raw ``DS_*`` at
  1e-5, the 4dp probability vectors at 2e-4 (their 4dp grid is not portable any
  tighter), and ``DP_*`` / ``delta_score`` only when ``DS_MAX`` clears the
  argmax noise floor;
* ``batch_annotate`` == ``annotate`` across the whole corpus -- with the same
  tiering (labels exact, probabilities at 2e-4, ``DS_*`` at 1e-5, positions
  gated on ``DS_MAX``).

The corpus + baseline are regenerated by ``tests/corpus/build_corpus.py`` and
``tests/corpus/regenerate_baseline.py``.
"""
import gzip
import json
import pathlib
from collections import defaultdict
from collections.abc import Iterator
from typing import Any

import pytest
from gain.annotation.annotatable import VCFAllele
from gain.annotation.annotation_factory import load_pipeline_from_yaml
from gain.annotation.annotation_pipeline import AnnotationPipeline
from gain.genomic_resources.repository import GenomicResourceRepo

from tests.corpus.pipeline_config import (
    DELTA_DS_TOL,
    DP_SOURCES,
    DS_MAX_GATE,
    DS_SOURCES,
    FLOAT_TOL,
    PROB_SOURCES,
    PROB_TOL,
    make_pipeline_yaml,
)

# Slow: ~9-10 min under TensorFlow. Runs in the gain-spliceai-integration job,
# not the fast per-PR spliceai_annotator step (see spliceai_annotator/pytest.ini
# and the "Trigger spliceai integration" stage in the root Jenkinsfile).
pytestmark = pytest.mark.integration

CORPUS_DIR = pathlib.Path(__file__).parent / "corpus"
MANIFEST = json.loads((CORPUS_DIR / "corpus_manifest.json").read_text())
with gzip.open(CORPUS_DIR / "baseline.json.gz", "rb") as _bf:
    BASELINE: dict[str, dict[str, Any]] = json.loads(_bf.read())

VARIANTS = MANIFEST["variants"]
DISTANCES = sorted({v["distance"] for v in VARIANTS})
_BY_DISTANCE: dict[int, list[dict[str, Any]]] = defaultdict(list)
for _v in VARIANTS:
    _BY_DISTANCE[_v["distance"]].append(_v)


def _allele(variant: dict[str, Any]) -> VCFAllele:
    return VCFAllele(
        variant["contig"], variant["pos"], variant["ref"], variant["alt"])


def _parse_prob(value: str) -> list[float]:
    """Flatten a ``;``-joined (per gene), ``,``-joined (per pos) prob string."""
    return [
        float(x)
        for gene_vec in value.split(";")
        for x in gene_vec.split(",")
    ]


def _assert_probs_close(vid: str, label: str, got: str, want: str) -> None:
    """Assert two 4dp probability strings agree within ``PROB_TOL``."""
    live = _parse_prob(got)
    ref = _parse_prob(want)
    assert len(live) == len(ref), f"{vid} {label} length"
    for g, e in zip(live, ref, strict=True):
        assert abs(g - e) <= PROB_TOL, f"{vid} {label}: {g} vs {e}"


def _delta_score_close(got: str, want: str) -> bool:
    """Compare ``delta_score`` robustly across fp environments.

    It is ``;``-joined per gene, each ``alt|gene|DS x4 (2dp)|DP x4 (int)``.
    Alt/gene and the DP integers must match exactly; the 2dp ``DS`` fields
    (which can round to adjacent values across fp environments) must agree
    within one 2dp unit -- the raw ``DS_*`` are pinned separately at
    ``FLOAT_TOL``.
    """
    got_genes = got.split(";")
    want_genes = want.split(";")
    if len(got_genes) != len(want_genes):
        return False
    for g, w in zip(got_genes, want_genes, strict=True):
        gf = g.split("|")
        wf = w.split("|")
        if len(gf) != 10 or len(wf) != 10:
            return False
        if gf[:2] != wf[:2] or gf[6:] != wf[6:]:  # alt|gene and DP integers
            return False
        if any(abs(float(a) - float(b)) > DELTA_DS_TOL
               for a, b in zip(gf[2:6], wf[2:6], strict=True)):  # 2dp DS
            return False
    return True


@pytest.fixture(scope="session")
def differential_pipelines(
    spliceai_grr: GenomicResourceRepo,
) -> Iterator[dict[int, AnnotationPipeline]]:
    """One opened all-16-attribute pipeline per corpus distance."""
    pipelines = {}
    for distance in DISTANCES:
        pipeline = load_pipeline_from_yaml(
            make_pipeline_yaml(distance), spliceai_grr)
        pipelines[distance] = pipeline.open()
    yield pipelines
    for pipeline in pipelines.values():
        pipeline.close()


def _assert_matches_baseline(
    variant: dict[str, Any], result: dict[str, Any],
) -> None:
    baseline = BASELINE[variant["id"]]

    if all(v is None for v in baseline.values()):
        assert all(v is None for v in result.values()), (
            f"{variant['id']}: expected all-None (rejected), got {result}")
        return

    # probability vectors: parse to floats, compare at PROB_TOL (4dp grid)
    for source in PROB_SOURCES:
        _assert_probs_close(
            variant["id"], source, result[source], baseline[source])

    # raw DS_* floats: full precision, portable across fp environments
    for source in DS_SOURCES:
        assert abs(result[source] - baseline[source]) <= FLOAT_TOL, (
            f"{variant['id']} {source}: {result[source]} vs {baseline[source]}")

    # DP_* and delta_score embed argmax positions -- only trustworthy above
    # the noise floor.
    if baseline["DS_MAX"] > DS_MAX_GATE:
        for source in DP_SOURCES:
            assert result[source] == baseline[source], (
                f"{variant['id']} {source}: {result[source]} vs "
                f"{baseline[source]}")
        assert _delta_score_close(
            result["delta_score"], baseline["delta_score"]), (
            f"{variant['id']} delta_score: {result['delta_score']} vs "
            f"{baseline['delta_score']}")


@pytest.mark.parametrize(
    "variant", VARIANTS, ids=[v["id"] for v in VARIANTS])
def test_matches_tensorflow_baseline(
    variant: dict[str, Any],
    differential_pipelines: dict[int, AnnotationPipeline],
) -> None:
    pipeline = differential_pipelines[variant["distance"]]
    result = pipeline.annotate(_allele(variant))
    _assert_matches_baseline(variant, result)


def _assert_batch_equals_sequential(
    variant: dict[str, Any],
    seq_result: dict[str, Any],
    batch_result: dict[str, Any],
) -> None:
    if all(v is None for v in seq_result.values()):
        assert all(v is None for v in batch_result.values()), (
            f"{variant['id']}: batch not all-None for rejected")
        return
    # Every annotated variant: batch must equal sequential.  Deletions with
    # ref_len-1 > distance -- the only case where the two padding paths would
    # structurally diverge (batch mis-reconstructs vs Illumina SpliceAI) --
    # are refused by the annotator, so they never reach here as annotated
    # results.  What remains is only batch fp non-associativity, which the
    # tiering below absorbs.
    for source in ("gene", "transcript_ids"):
        assert batch_result[source] == seq_result[source], (
            f"{variant['id']} {source}: batch != sequential")
    # probability vectors can flip a 4dp unit under batch fp non-associativity
    for source in PROB_SOURCES:
        _assert_probs_close(
            variant["id"], source, batch_result[source], seq_result[source])
    # raw DS_* floats at full precision
    for source in DS_SOURCES:
        assert abs(batch_result[source] - seq_result[source]) <= FLOAT_TOL, (
            f"{variant['id']} {source}: batch {batch_result[source]} vs "
            f"sequential {seq_result[source]}")
    # DP_* and delta_score positions: trustworthy only above the noise floor
    # (a weak channel's argmax can flip under batch fp non-associativity, even
    # when DS_MAX is high -- the same near-tie effect the baseline gates on).
    if seq_result["DS_MAX"] > DS_MAX_GATE:
        for source in DP_SOURCES:
            assert batch_result[source] == seq_result[source], (
                f"{variant['id']} {source}: batch != sequential")
        assert _delta_score_close(
            batch_result["delta_score"], seq_result["delta_score"]), (
            f"{variant['id']} delta_score: batch != sequential")


@pytest.mark.parametrize("distance", DISTANCES)
def test_batch_equals_sequential(
    distance: int,
    differential_pipelines: dict[int, AnnotationPipeline],
) -> None:
    pipeline = differential_pipelines[distance]
    variants = _BY_DISTANCE[distance]
    alleles = [_allele(v) for v in variants]

    seq_results = [pipeline.annotate(a) for a in alleles]
    batch_results = pipeline.batch_annotate(alleles)
    assert len(batch_results) == len(variants)

    for variant, seq_result, batch_result in zip(
            variants, seq_results, batch_results, strict=True):
        _assert_batch_equals_sequential(variant, seq_result, batch_result)
