# pylint: disable=W0621,C0114,C0116,W0212,W0613
"""Differential test harness for the SpliceAI annotator (issue #320).

Pins all 16 attributes of today's TensorFlow output on a frozen hg38/GENCODE
fixture corpus, so the upcoming ONNX migration (#297/#299) has real ground
truth to check against.  Two independent checks per variant:

* live annotation vs the committed TensorFlow ``baseline.json.gz`` -- tiered by
  measured stability (probabilities + ``DS_*`` at ~1e-5; ``DP_*`` and
  ``delta_score`` only when ``DS_MAX`` clears the argmax noise floor);
* ``batch_annotate`` == ``annotate`` across the whole corpus -- exact on the
  formatted attributes, ~1e-5 on the raw ``DS_*`` floats.

The corpus + baseline are regenerated by ``tests/corpus/build_corpus.py`` and
``tests/corpus/regenerate_baseline.py``.
"""
import gzip
import json
import pathlib
from collections import defaultdict
from collections.abc import Iterator
from typing import Any

import pytest
from gain.annotation.annotatable import VCFAllele
from gain.annotation.annotation_factory import load_pipeline_from_yaml
from gain.annotation.annotation_pipeline import AnnotationPipeline
from gain.genomic_resources.repository import GenomicResourceRepo

from tests.corpus.pipeline_config import (
    DP_SOURCES,
    DS_MAX_GATE,
    DS_SOURCES,
    FLOAT_TOL,
    PROB_SOURCES,
    make_pipeline_yaml,
)

CORPUS_DIR = pathlib.Path(__file__).parent / "corpus"
MANIFEST = json.loads((CORPUS_DIR / "corpus_manifest.json").read_text())
with gzip.open(CORPUS_DIR / "baseline.json.gz", "rb") as _bf:
    BASELINE: dict[str, dict[str, Any]] = json.loads(_bf.read())

VARIANTS = MANIFEST["variants"]
DISTANCES = sorted({v["distance"] for v in VARIANTS})
_BY_DISTANCE: dict[int, list[dict[str, Any]]] = defaultdict(list)
for _v in VARIANTS:
    _BY_DISTANCE[_v["distance"]].append(_v)


def _allele(variant: dict[str, Any]) -> VCFAllele:
    return VCFAllele(
        variant["contig"], variant["pos"], variant["ref"], variant["alt"])


def _parse_prob(value: str) -> list[float]:
    """Flatten a ``;``-joined (per gene), ``,``-joined (per pos) prob string."""
    return [
        float(x)
        for gene_vec in value.split(";")
        for x in gene_vec.split(",")
    ]


@pytest.fixture(scope="session")
def differential_pipelines(
    spliceai_grr: GenomicResourceRepo,
) -> Iterator[dict[int, AnnotationPipeline]]:
    """One opened all-16-attribute pipeline per corpus distance."""
    pipelines = {}
    for distance in DISTANCES:
        pipeline = load_pipeline_from_yaml(
            make_pipeline_yaml(distance), spliceai_grr)
        pipelines[distance] = pipeline.open()
    yield pipelines
    for pipeline in pipelines.values():
        pipeline.close()


def _assert_matches_baseline(
    variant: dict[str, Any], result: dict[str, Any],
) -> None:
    baseline = BASELINE[variant["id"]]

    if all(v is None for v in baseline.values()):
        assert all(v is None for v in result.values()), (
            f"{variant['id']}: expected all-None (rejected), got {result}")
        return

    # probability vectors: parse to floats, compare at tolerance
    for source in PROB_SOURCES:
        live = _parse_prob(result[source])
        want = _parse_prob(baseline[source])
        assert len(live) == len(want), f"{variant['id']} {source} length"
        for got, exp in zip(live, want, strict=True):
            assert abs(got - exp) <= FLOAT_TOL, (
                f"{variant['id']} {source}: {got} vs {exp}")

    # raw DS_* floats: stable under near-ties, compare at tolerance
    for source in DS_SOURCES:
        assert abs(result[source] - baseline[source]) <= FLOAT_TOL, (
            f"{variant['id']} {source}: {result[source]} vs {baseline[source]}")

    # DP_* and delta_score embed argmax positions -- only trustworthy above
    # the noise floor.
    if baseline["DS_MAX"] > DS_MAX_GATE:
        for source in DP_SOURCES:
            assert result[source] == baseline[source], (
                f"{variant['id']} {source}: {result[source]} vs "
                f"{baseline[source]}")
        assert result["delta_score"] == baseline["delta_score"], (
            f"{variant['id']} delta_score")


@pytest.mark.parametrize(
    "variant", VARIANTS, ids=[v["id"] for v in VARIANTS])
def test_matches_tensorflow_baseline(
    variant: dict[str, Any],
    differential_pipelines: dict[int, AnnotationPipeline],
) -> None:
    pipeline = differential_pipelines[variant["distance"]]
    result = pipeline.annotate(_allele(variant))
    _assert_matches_baseline(variant, result)


def _diverges_batch_vs_sequential(variant: dict[str, Any]) -> bool:
    """Whether the two padding paths are known to structurally diverge.

    ``_prediction_padding_sequential`` and ``_prediction_padding_batch`` trim a
    deletion's alt window differently once the trimmed reference is longer than
    the model half-window -- i.e. ``ref_len - 1 > distance`` (the case the issue
    documents and the ``del_long`` corpus variants exercise).  In that regime
    batch != sequential is expected behaviour, so equality is not asserted; the
    sequential output is still pinned against the TensorFlow baseline.
    """
    return bool(len(variant["ref"]) - 1 > variant["distance"])


def _assert_batch_equals_sequential(
    variant: dict[str, Any],
    seq_result: dict[str, Any],
    batch_result: dict[str, Any],
) -> None:
    if all(v is None for v in seq_result.values()):
        assert all(v is None for v in batch_result.values()), (
            f"{variant['id']}: batch not all-None for rejected")
        return
    if _diverges_batch_vs_sequential(variant):
        # documented ref_len-1 > distance padding divergence: the paths
        # intentionally differ.  Exercise the batch path and only check it
        # still yields a structurally valid (non-None) result.
        assert not all(v is None for v in batch_result.values()), (
            f"{variant['id']}: batch unexpectedly all-None "
            "in the padding-divergence regime")
        return
    # exact on the formatted attributes
    for source in (*DP_SOURCES, *PROB_SOURCES, "delta_score",
                   "gene", "transcript_ids"):
        assert batch_result[source] == seq_result[source], (
            f"{variant['id']} {source}: batch != sequential")
    # tolerance on the raw DS_* floats (fp non-associativity of batch padding)
    for source in DS_SOURCES:
        assert abs(batch_result[source] - seq_result[source]) <= FLOAT_TOL, (
            f"{variant['id']} {source}: batch {batch_result[source]} vs "
            f"sequential {seq_result[source]}")


@pytest.mark.parametrize("distance", DISTANCES)
def test_batch_equals_sequential(
    distance: int,
    differential_pipelines: dict[int, AnnotationPipeline],
) -> None:
    pipeline = differential_pipelines[distance]
    variants = _BY_DISTANCE[distance]
    alleles = [_allele(v) for v in variants]

    seq_results = [pipeline.annotate(a) for a in alleles]
    batch_results = pipeline.batch_annotate(alleles)
    assert len(batch_results) == len(variants)

    for variant, seq_result, batch_result in zip(
            variants, seq_results, batch_results, strict=True):
        _assert_batch_equals_sequential(variant, seq_result, batch_result)
