# Generated by Django 5.2.13 on 2026-05-05 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0037_merge_20260421_1200"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuotaRefreshLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "daily_quota_refresh_log",
            },
        ),
        migrations.CreateModel(
            name="MonthlyQuotaRefreshLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "monthly_quota_refresh_log",
            },
        ),
    ]
