# Generated by Django 5.2.13 on 2026-05-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0038_dailymonthly_quota_refresh_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_unlimited",
            field=models.BooleanField(default=False),
        ),
    ]
