# Generated by Django 5.2.13 on 2026-05-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0039_user_is_unlimited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anonymoususerquota",
            name="daily_allele_queries",
        ),
        migrations.RemoveField(
            model_name="anonymoususerquota",
            name="extra_allele_queries",
        ),
        migrations.RemoveField(
            model_name="anonymoususerquota",
            name="monthly_allele_queries",
        ),
        migrations.RemoveField(
            model_name="userquota",
            name="daily_allele_queries",
        ),
        migrations.RemoveField(
            model_name="userquota",
            name="extra_allele_queries",
        ),
        migrations.RemoveField(
            model_name="userquota",
            name="monthly_allele_queries",
        ),
    ]
