# Generated by Django 5.2.13 on 2026-05-12 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "web_annotation",
            "0040_remove_anonymoususerquota_daily_allele_queries_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_jobs", models.IntegerField(default=0)),
                ("monthly_jobs", models.IntegerField(default=0)),
                ("daily_variants", models.IntegerField(default=0)),
                ("monthly_variants", models.IntegerField(default=0)),
                ("daily_attributes", models.IntegerField(default=0)),
                ("monthly_attributes", models.IntegerField(default=0)),
                (
                    "last_daily_reset",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_monthly_reset",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("extra_jobs", models.IntegerField(default=0)),
                ("extra_variants", models.IntegerField(default=0)),
                ("extra_attributes", models.IntegerField(default=0)),
                ("session_id", models.CharField(max_length=1024, unique=True)),
            ],
            options={
                "db_table": "session_quotas",
            },
        ),
    ]
