# Generated by Django 5.2.13 on 2026-06-14 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import Count, Max


def _dedup_user_quotas(
    apps: StateApps,
    schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    """Drop duplicate quota rows before the unique constraints land.

    Existing deployments may already hold duplicate ``UserQuota`` /
    ``AnonymousUserQuota`` rows created by the pre-fix ``get_or_create``
    race. Keep the newest row per user / per ip and delete the rest, so the
    AlterField operations that add the uniqueness guarantees do not fail on
    production data.

    Policy / tradeoff: duplicates are rare race artifacts. We keep the
    newest row (``Max("id")``) and discard the older ones. Any quota
    consumption recorded on a discarded row is forgiven -- a user could
    regain a little quota. This is a deliberate, accepted choice: the rows
    are near-duplicates created within the same request window, the lost
    consumption is tiny, and "keep newest" is simpler and more predictable
    than trying to merge accumulated counters across the duplicates.
    """
    user_quota = apps.get_model("web_annotation", "UserQuota")
    dup_users = (
        user_quota.objects.values("user")
        .annotate(n=Count("id"), keep=Max("id"))
        .filter(n__gt=1)
    )
    for row in dup_users:
        user_quota.objects.filter(user=row["user"]).exclude(
            id=row["keep"]).delete()

    anon_quota = apps.get_model("web_annotation", "AnonymousUserQuota")
    dup_ips = (
        anon_quota.objects.values("ip")
        .annotate(n=Count("id"), keep=Max("id"))
        .filter(n__gt=1)
    )
    for row in dup_ips:
        anon_quota.objects.filter(ip=row["ip"]).exclude(
            id=row["keep"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0041_add_session_quota'),
    ]

    operations = [
        migrations.RunPython(
            _dedup_user_quotas,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='anonymoususerquota',
            name='ip',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL),
        ),
    ]
