"""settingsdef
Django settings for gpf_web_annotation project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import logging
import os
import pathlib
from typing import Any

from django.core.exceptions import ImproperlyConfigured
from gain.genomic_resources.repository_factory import (
    get_default_grr_definition_path,
)

DEFAULT_DATA_DIR = str(pathlib.Path(__file__).parent.parent / "data")

# Dir for all data storage
DATA_STORAGE_DIR = os.environ.get("GPFWA_DATA_STORAGE", DEFAULT_DATA_DIR)

# Create the dir we will ACTUALLY use -- not DEFAULT_DATA_DIR, which lives
# inside the installed package. This used to mkdir DEFAULT_DATA_DIR at import
# time, BEFORE the GPFWA_DATA_STORAGE override above was read, so pointing the
# override at a writable volume did not help: the import still wrote into
# site-packages. That only worked because every container ran as root; a
# non-root uid dies here with EPERM before Django starts (gain#274).
# `exist_ok` also drops a race between concurrently-importing workers.
os.makedirs(DATA_STORAGE_DIR, exist_ok=True)

# Subdir to store uploaded annotation configurations in
ANNOTATION_CONFIG_STORAGE_DIR = f"{DATA_STORAGE_DIR}/annotation-configs"
# Subdir to store uploaded files in before they are annotated
JOB_INPUT_STORAGE_DIR = f"{DATA_STORAGE_DIR}/job-inputs"
# Subdir to store results of annotation in
JOB_RESULT_STORAGE_DIR = f"{DATA_STORAGE_DIR}/job-results"
# Scratch dir for annotators built by the pipeline cache (the editor /
# pipeline_status path). gain's build_annotation_pipeline defaults work_dir to
# a RELATIVE Path("./work") -- a CLI convention, since annotate_* run in the
# user's own writable cwd. A server does not have one: "./work" resolves
# against the process cwd, which is root-owned in the container, so every
# pipeline build EPERMs as a non-root uid (gain#276). The job path already
# passes an explicit work_dir (tasks.py); this gives the cache one too.
PIPELINE_WORK_DIR = f"{DATA_STORAGE_DIR}/pipeline-work"

PIPELINES_STORAGE_DIR = f"{DATA_STORAGE_DIR}/pipelines"

QUOTAS = {
    "daily_jobs": 20,
    "filesize": "64M",
    "disk_space": "2048M",
}

QUERY_QUOTAS = {
    "anonymous": {
        "daily_jobs": 10,
        "monthly_jobs": 100,
        "daily_variants": 100_000,
        "monthly_variants": 1_000_000,
        "daily_attributes": 1_000_000,
        "monthly_attributes": 10_000_000,
    },
    "user": {
        "daily_jobs": 100,
        "monthly_jobs": 1_000,
        "daily_variants": 1_000_000,
        "monthly_variants": 10_000_000,
        "daily_attributes": 10_000_000,
        "monthly_attributes": 100_000_000,
    },
}

JOB_CLEANUP_INTERVAL_DAYS = 30


# Age (in hours) past which a terminal anonymous job is reaped by the
# ``cleanup_anonymous_jobs`` janitor. Anonymous jobs are no longer deleted on
# WebSocket disconnect (iossifovlab/gain#216), so a scheduled janitor bounds
# their result-file lifetime instead. Active (WAITING/IN_PROGRESS) jobs are
# never reaped regardless of age.
#
# Parsed defensively: a non-numeric GPFWA_ANONYMOUS_JOB_TTL_HOURS must not
# raise at settings import and take down the ENTIRE Django service -- only the
# janitor cares about this value. Fall back to the 24h default instead; the
# command re-validates it (rejecting negatives, re-coercing a bad value).
def _parse_ttl_hours(raw: str, default: int = 24) -> int:
    try:
        return int(raw)
    except ValueError:
        return default


ANONYMOUS_JOB_TTL_HOURS = _parse_ttl_hours(
    os.environ.get("GPFWA_ANONYMOUS_JOB_TTL_HOURS", "24"))


# Number of reverse proxies in front of this application, i.e. how many
# trailing entries of ``X-Forwarded-For`` were appended by infrastructure we
# trust. It is the ONE knob deciding which entry of the header is the client
# (iossifovlab/gain#667) -- it governs both DRF's throttle bucket (DRF reads
# it as ``NUM_PROXIES``) and ``web_annotation.utils.get_ip_from_request``,
# which keys the anonymous quota. Semantics are DRF's, verbatim:
#
#   unset -- pre-#667 behaviour, unchanged: the throttle keys on the whole
#            header and the quota on its leftmost (client-supplied) entry.
#   0     -- ``REMOTE_ADDR`` only; ``X-Forwarded-For`` is ignored.
#   N > 0 -- the Nth entry counted from the RIGHT of the header.
#
# Deliberately left unset by default: #660 owns choosing the deployed value
# (it needs the proxy chain in front of gain.iossifovlab.com confirmed) and
# wiring it through gain-infra. Until then this is a no-op knob.
#
# Unparseable values fail HERE, at startup. Unlike
# GPFWA_ANONYMOUS_JOB_TTL_HOURS above -- where only a janitor cares and a
# silent default is the safer failure -- a wrong hop count silently mis-keys
# every rate limit and every anonymous quota, so a typo must not boot.
def _parse_num_proxies(raw: str | None) -> int | None:
    """Parse the trusted-proxy count; refuse anything not a natural number."""
    if raw is None or not raw.strip():
        logging.getLogger(__name__).warning(
            "GPFWA_NUM_PROXIES is not set: the client IP is taken from the "
            "client-supplied part of X-Forwarded-For (leftmost entry) and the "
            "throttle bucket keys on the whole header. See "
            "iossifovlab/gain#667 and iossifovlab/gain#660.",
        )
        return None
    invalid = ImproperlyConfigured(
        f"GPFWA_NUM_PROXIES must be a non-negative integer, got {raw!r}",
    )
    # Do not delegate the shape check to int(): it accepts PEP 515 underscore
    # separators AND every Unicode digit, so `int("1_0")` is 10, and so is
    # int() of the Arabic-Indic, fullwidth or Thai spelling of ten -- a typo
    # would boot with ten trusted hops instead of failing. isdigit() alone is
    # not enough either: it is true for those same Unicode digits. The count
    # must be plain ASCII decimal.
    # A separate `< 0` check would be dead code: the guard admits only
    # [0-9]+, so a leading sign never reaches int().
    candidate = raw.strip()
    if not (candidate.isascii() and candidate.isdigit()):
        raise invalid
    return int(candidate)


# Underscore-prefixed so `from .settings_default import *` does NOT re-export
# it: the hop count must be readable in exactly one way, as
# ``REST_FRAMEWORK["NUM_PROXIES"]``. A bare ``settings.NUM_PROXIES`` would be a
# second source of truth that also bypasses DRF's setting_changed reload, so a
# test override would move one reader and not the other.
_NUM_PROXIES = _parse_num_proxies(os.environ.get("GPFWA_NUM_PROXIES"))

GRR_DEFINITION_PATH = get_default_grr_definition_path()

# Hristo kaza
APPEND_SLASH = False

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get(
    "GPFWA_SECRET_KEY",
    "Ohze5Led4wi5xeirochee7mai8daet4thae7ZuquahmeeXaph6Ai5Riphiazohchaed8eec"
    "aena6jongietoh9Ohye2ahpee7iduequ5iboovo8lue1phaib",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["localhost", "*", os.environ.get("GPFWA_PUBLIC_NAME", "*")]
if os.environ.get("GPFWA_PUBLIC_NAME"):
    CSRF_TRUSTED_ORIGINS = [
        f"https://{os.environ.get('GPFWA_PUBLIC_NAME')}",
    ]

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "web_annotation.apps.WebAnnotationConfig",
]

# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "web_annotation.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "web_annotation.wsgi.application"
ASGI_APPLICATION = "web_annotation.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get("GPFWA_DB_HOST"):
    DATABASES: dict[str, Any] = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("GPFWA_DB_NAME"),
            "USER": os.environ.get("GPFWA_DB_USER"),
            "PASSWORD": os.environ.get("GPFWA_DB_PASSWORD"),
            "HOST": os.environ.get("GPFWA_DB_HOST"),
            "PORT": os.environ.get("GPFWA_DB_PORT"),
        },
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            # DATA_STORAGE_DIR, not DEFAULT_DATA_DIR: that is the dir we
            # create above. Keying the db off DEFAULT_DATA_DIR would put it
            # inside site-packages, and would now point at a dir that is not
            # created at all when GPFWA_DATA_STORAGE is set.
            "NAME": f"{DATA_STORAGE_DIR}/db.sqlite3",
            "USER": "",
            "PASSWORD": "",
            "HOST": "",
            "PORT": "",
        },
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
        "django.contrib.auth.password_validation"
        ".UserAttributeSimilarityValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Timezone whose calendar day/month boundary the quota-refresh commands
# (refreshdaily / refreshmonthly) use for their "already ran today/this
# month" guard. Defaults to UTC; set GPFWA_QUOTA_RESET_TIMEZONE to the
# deployment's local zone (e.g. "America/New_York") so the guard aligns
# with locally-scheduled timers.
QUOTA_RESET_TIMEZONE = os.environ.get("GPFWA_QUOTA_RESET_TIMEZONE", "UTC")


# Static files (CSS, JavaScript, Images).
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Uploaded static files

MEDIA_URL = "/media/"
MEDIA_ROOT = "media-root"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": None,
    "PAGE_SIZE": None,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.BasicAuthentication",
    ),
    # Also read by web_annotation.utils.get_ip_from_request, so the throttle
    # bucket and the anonymous quota key cannot drift (iossifovlab/gain#667);
    # see the GPFWA_NUM_PROXIES block above.
    "NUM_PROXIES": _NUM_PROXIES,
    "DEFAULT_THROTTLE_RATES": {
        # Named after the endpoint it reaches, not after DRF's global "user"
        # scope: nothing installs UserRateThrottle globally here, so this rate
        # only ever budgeted the single-allele annotate view (gain#694).
        "annotate": "10/minute",
        # The pipeline editor validates as the user edits, so this bucket is
        # sized for a keystroke cadence, not for expensive work -- see
        # web_annotation.pipelines.throttling.
        "pipeline_validate": "120/minute",

        # The authentication surface (gain#694). Every family gets its own
        # bucket: a login attempt and a password-reset mail have entirely
        # different costs. See web_annotation.throttling for which endpoint
        # each scope reaches.
        #
        # Login: ten a minute is well above a human mistyping a password and
        # far below anything that makes credential stuffing worthwhile.
        "auth_login": "10/minute",
        # Registration and password reset both end in an outbound mail, so
        # they are budgeted per hour rather than per minute. Three an hour
        # only leaves room for a legitimate user because the reset throttle
        # charges the POSTs and not the GET that renders the form -- see
        # web_annotation.throttling.PasswordResetRateThrottle.
        "auth_register": "5/hour",
        "auth_password_reset": "3/hour",
        # Redeeming a code from a mail: a user follows the link once, maybe
        # reloads. The bucket only has to bound code guessing.
        "auth_confirm": "20/hour",

        # The per-submitted-address axis of the dual key. Deliberately looser
        # than the matching per-IP rate above -- a tight identifier bucket is
        # a lockout denial-of-service, because anyone who knows an address
        # could burn that user's budget from anywhere. It is sized to catch
        # distributed spraying (many hosts, one account), which needs far more
        # attempts than one legitimate user makes, not to be the primary
        # limit. Each is three times its per-IP counterpart.
        "auth_login_identifier": "30/minute",
        "auth_password_reset_identifier": "9/hour",
    },
}

# Project-specific stuff
AUTH_USER_MODEL = "web_annotation.User"

# Email related settings
RESET_PASSWORD_TIMEOUT_HOURS = 24

USERS_ACTIVATED_BY_DEFAULT = True

EMAIL_HOST = os.environ.get("GPFWA_EMAIL_HOST", "localhost")
EMAIL_USE_TLS = (
    os.environ.get("GPFWA_EMAIL_USE_TLS", "").strip().lower() == "true"
)
EMAIL_HOST_USER = os.environ.get("GPFWA_EMAIL_HOST_USER", None)
EMAIL_HOST_PASSWORD = os.environ.get("GPFWA_EMAIL_HOST_PASSWORD", None)

EMAIL_PORT = os.environ.get("GPFWA_EMAIL_PORT", 1025)
if EMAIL_PORT is not None:
    EMAIL_PORT = int(EMAIL_PORT)

DEFAULT_FROM_EMAIL = os.environ.get(
    "GPFWA_DEFAULT_FROM_EMAIL", "no-reply@iossifovlab.com")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_VERIFICATION_ENDPOINT = os.environ.get(
    "GPFWA_EMAIL_VERIFICATION_ENDPOINT", "http://localhost:8000")
EMAIL_REDIRECT_ENDPOINT = os.environ.get(
    "GPFWA_EMAIL_REDIRECT_ENDPOINT", "http://localhost:4200")


STATIC_URL = "/static/"
STATIC_ROOT = "static-root"

LOG_DIR = os.environ.get("GPFWA_LOG_DIR", f"{DATA_STORAGE_DIR}/logs")
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d "
            "%(thread)d %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "logdebug": {
            "level": "DEBUG",
            "class": "logging.handlers.WatchedFileHandler",
            "filename": f"{LOG_DIR}/gpfwa-debug.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "daphne.http_protocol": {
            "handlers": ["console", "logdebug"],
            "propagate": True,
            "level": "INFO",
        },
        "django": {
            "handlers": ["console", "logdebug"],
            "propagate": True,
            "level": "INFO",
        },
        "fsspec": {
            "handlers": ["console", "logdebug"],
            "level": "WARNING",
            "propagate": True,
        },
        "gain.effect_annotation": {
            "handlers": ["console", "logdebug"],
            "level": "INFO",
            "propagate": True,
        },
        "matplotlib": {
            "handlers": ["console", "logdebug"],
            "level": "INFO",
            "propagate": True,
        },
        "": {
            "handlers": ["console", "logdebug"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

ANNOTATION_MAX_WORKERS = 4
PIPELINES_CACHE_SIZE = 256

ANNOTATION_TASK_TIMEOUT = 60 * 60 * 2  # 2 hours

DEFAULT_PIPELINE: str | None = "pipeline/hg38_clinical_annotation"
