#!/usr/bin/env bash
# Stand up a single daphne server for the #164 load harness (fallback (b)).
#
# Uses settings_e2e against the in-repo test GRR fixture (t4c8/t4c8_pipeline)
# and a throwaway sqlite DB -- no postgres, no /mnt/cephfs, no prebuilt image.
# A FRESH process => the target pipeline starts COLD, so the first harness run
# sees real build contention. Set GPFWA_BUILD_DELAY_SECONDS to inject the
# deterministic slow-build delay.
#
# Usage:
#   GPFWA_BUILD_DELAY_SECONDS=0.4 PORT=21011 \
#     bash web_annotation/loadtest/run_daphne_server.sh
#
# Run this from the web_api/ directory with the gain venv active (or it will
# activate ../.venv if present).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB_API_DIR="$(cd "${HERE}/../.." && pwd)"
REPO_ROOT="$(cd "${WEB_API_DIR}/.." && pwd)"
cd "${WEB_API_DIR}"

# Activate the gain venv if not already active.
if [[ -z "${VIRTUAL_ENV:-}" && -f "${REPO_ROOT}/.venv/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source "${REPO_ROOT}/.venv/bin/activate"
fi

PORT="${PORT:-21011}"
GRR_DIR="${WEB_API_DIR}/web_annotation/tests/fixtures/grr"
GRR_FIXTURE="${GRR_DIR}/grr_definition.yaml"

# The fixture grr_definition.yaml is generated by the test suite and is not
# checked in; (re)write it here so this works on any checkout (incl. the sync
# baseline worktree).
cat > "${GRR_FIXTURE}" <<YAML
id: test
type: dir
directory: ${GRR_DIR}
YAML

# Run the worktree's own web_annotation (not whatever the shared venv installed
# editable from another checkout) so the baseline really measures baseline code.
export PYTHONPATH="${WEB_API_DIR}${PYTHONPATH:+:${PYTHONPATH}}"

# Throwaway data dir + sqlite DB so runs don't collide / persist a warm cache.
DATA_DIR="$(mktemp -d)"
export GPFWA_DATA_STORAGE="${DATA_DIR}"
export GRR_DEFINITION_FILE="${GRR_FIXTURE}"
export DJANGO_SETTINGS_MODULE="web_annotation.settings_e2e"
export GPFWA_SECRET_KEY="${GPFWA_SECRET_KEY:-django-insecure-loadtest-164}"
export GPFWA_BUILD_DELAY_SECONDS="${GPFWA_BUILD_DELAY_SECONDS:-0}"

echo "[run_daphne_server] data dir:    ${DATA_DIR}"
echo "[run_daphne_server] GRR def:     ${GRR_FIXTURE}"
echo "[run_daphne_server] build delay: ${GPFWA_BUILD_DELAY_SECONDS}s"
echo "[run_daphne_server] port:        ${PORT}"

python -m django migrate --noinput >/dev/null

# An unlimited user lets the harness bypass the anonymous UserRateThrottle
# (10/min) and the single-allele quota, so all K requests reach the build wait.
LOADTEST_USER="${LOADTEST_USER:-loadtest@example.com}"
LOADTEST_PASS="${LOADTEST_PASS:-secret}"
python -m django create_user "${LOADTEST_USER}" "${LOADTEST_PASS}" >/dev/null 2>&1 || true
python -m django set_unlimited "${LOADTEST_USER}" >/dev/null 2>&1 || true
echo "[run_daphne_server] unlimited user: ${LOADTEST_USER} / ${LOADTEST_PASS}"

exec daphne -b 127.0.0.1 -p "${PORT}" web_annotation.asgi:application
